version: '3.6'
services:

  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
      - ${WORDPRESS_DATA_DIR}:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${DATABASE_USER}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD}
      - |
        WORDPRESS_CONFIG_EXTRA=
        define( 'AS3CF_SETTINGS', serialize( array(
        // Storage Provider ('aws', 'do', 'gcp')
        'provider' => 'aws',
        // Access Key ID for Storage Provider (aws and do only, replace '*')
        'access-key-id' => '${IAM_ACCESS}',
        // Secret Access Key for Storage Providers (aws and do only, replace '*')
        'secret-access-key' => '${IAM_SECRET}',
        // Bucket to upload files to
        'bucket' => '${S3_BUCKET}',
        // Bucket region (e.g. 'us-west-1' - leave blank for default region)
        'region' => 'eu-west-3',
        // Automatically copy files to bucket on upload
        'copy-to-s3' => true,
        // Enable object prefix, useful if you use your bucket for other files
        'enable-object-prefix' => true,
        // Object prefix to use if 'enable-object-prefix' is 'true'
        'object-prefix' => 'wp-content/uploads/',
        // Rewrite file URLs to bucket
        'serve-from-s3' => true,
        ) ) );
    restart: always
    ports:
        - 80:80
        
  # Command line interface to wordpress
  wpcli:
    build: ./wpcli/
    image: wpcli
    container_name: ${COMPOSE_PROJECT_NAME}_wpcli
    volumes:
      - ${WORDPRESS_DATA_DIR}:/var/www/html
    working_dir: /var/www/html

# Check availability of essential services
  healthcheck:
    image: wpcli
    build: ./wpcli/
    container_name: ${COMPOSE_PROJECT_NAME}_healthcheck
    command: sh -c "/wait"
    environment:
      - WAIT_HOSTS=${WORDPRESS_DB_HOST}:3306, wordpress:80
      - WAIT_BEFORE_HOSTS=${WAIT_BEFORE_HOSTS}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL}
      - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT}
